# Generated by Django 6.0.2 on 2026-03-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimages",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
