# Generated by Django 6.0.2 on 2026-03-08 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="following_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
